"""PA#4: Educational CBC mode using toy PRF block cipher."""

from backend.core.pa2_prf.ggm_prf import simple_prf
from backend.core.utils.bit_utils import bytes_to_hex, hex_to_bytes, xor_bytes

BLOCK_BYTES = 4


def _pkcs7_pad(data: bytes, block_size: int = BLOCK_BYTES) -> bytes:
    pad_len = block_size - (len(data) % block_size)
    return data + bytes([pad_len]) * pad_len


def _pkcs7_unpad(data: bytes, block_size: int = BLOCK_BYTES) -> bytes:
    if not data or len(data) % block_size != 0:
        raise ValueError("Invalid padded data length")
    pad_len = data[-1]
    if pad_len < 1 or pad_len > block_size:
        raise ValueError("Invalid PKCS#7 padding length")
    if data[-pad_len:] != bytes([pad_len]) * pad_len:
        raise ValueError("Invalid PKCS#7 padding bytes")
    return data[:-pad_len]


def _toy_block_mask(key_hex: str) -> bytes:
    return bytes.fromhex(simple_prf(key_hex, "1010101010101010")["output"])[:BLOCK_BYTES]


def _toy_block_cipher(key_hex: str, block: bytes) -> bytes:
    mask = _toy_block_mask(key_hex)[: len(block)]
    return xor_bytes(block, mask)


def cbc_encrypt(key_hex: str, plaintext: bytes, iv_hex: str) -> dict:
    """Encrypt bytes in CBC mode with toy PRF-based block cipher."""
    iv = hex_to_bytes(iv_hex)
    if len(iv) != BLOCK_BYTES:
        raise ValueError(f"IV must be {BLOCK_BYTES} bytes")

    padded = _pkcs7_pad(plaintext, BLOCK_BYTES)
    blocks = [padded[i : i + BLOCK_BYTES] for i in range(0, len(padded), BLOCK_BYTES)]

    prev = iv
    cipher_blocks = []
    steps = [
        f"Input plaintext hex = {bytes_to_hex(plaintext)}",
        f"PKCS#7 padded plaintext = {bytes_to_hex(padded)}",
        f"CBC IV = {iv_hex.lower()}",
    ]

    for index, block in enumerate(blocks, start=1):
        mixed = xor_bytes(block, prev)
        encrypted = _toy_block_cipher(key_hex, mixed)
        cipher_blocks.append(encrypted)
        prev = encrypted
        steps.append(
            f"Block {index}: X = P xor C_prev = {bytes_to_hex(mixed)}, C = E_k(X) = {bytes_to_hex(encrypted)}"
        )

    ciphertext = b"".join(cipher_blocks)
    return {
        "result": {
            "mode": "CBC",
            "iv": iv_hex.lower(),
            "ciphertext": bytes_to_hex(ciphertext),
            "blocks": [bytes_to_hex(block) for block in cipher_blocks],
        },
        "steps": steps,
    }


def cbc_decrypt(key_hex: str, ciphertext_hex: str, iv_hex: str) -> dict:
    """Decrypt CBC ciphertext generated by cbc_encrypt."""
    iv = hex_to_bytes(iv_hex)
    ciphertext = hex_to_bytes(ciphertext_hex)
    if len(iv) != BLOCK_BYTES:
        raise ValueError(f"IV must be {BLOCK_BYTES} bytes")
    if len(ciphertext) % BLOCK_BYTES != 0:
        raise ValueError("Ciphertext length must be a multiple of block size")

    blocks = [ciphertext[i : i + BLOCK_BYTES] for i in range(0, len(ciphertext), BLOCK_BYTES)]
    prev = iv
    plain_blocks = []
    steps = [f"CBC decrypt IV = {iv_hex.lower()}"]

    for index, c_block in enumerate(blocks, start=1):
        decrypted = _toy_block_cipher(key_hex, c_block)
        p_block = xor_bytes(decrypted, prev)
        plain_blocks.append(p_block)
        steps.append(
            f"Block {index}: D_k(C)={bytes_to_hex(decrypted)}, P = D xor C_prev = {bytes_to_hex(p_block)}"
        )
        prev = c_block

    padded = b"".join(plain_blocks)
    plaintext = _pkcs7_unpad(padded, BLOCK_BYTES)
    steps.append(f"Unpadded plaintext hex = {bytes_to_hex(plaintext)}")

    return {
        "result": {
            "mode": "CBC",
            "plaintext_hex": bytes_to_hex(plaintext),
            "plaintext": plaintext.decode("utf-8", errors="replace"),
        },
        "steps": steps,
    }
